# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

version: 2

defaults: &defaults
  working_directory: ~/repo/api
  docker:
    - image: circleci/node:10.16.0

jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
      #- run: cp dev.env .env
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: ~/repo
          paths:
            - api/
  build:
    <<: *defaults
    working_directory: ~/repo/api
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - api
  lint:
    <<: *defaults
    working_directory: ~/repo/api
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Lint
          command: yarn lint

  test:
    <<: *defaults
    working_directory: ~/repo/api
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Test
          command: |
            yarn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - setup
      - build:
          requires:
            - setup
      - lint:
          requires:
            - build
      - test:
          requires:
            - build